/*
 * Copyright https://github.com/stathry/generator All rights reserved.
 */
package org.stathry.commons.pojo;

import java.util.Date;

/**
 * 
 * @author Auto-generated by FreeMarker
 * @date 2018-07-20 10:26
 */  
 
public class Actor {

    /**  */
    private Integer actorId;
      
    /**  */
    private String firstName;
      
    /**  */
    private String lastName;
      
    /**  */
    private Date lastUpdate;
      
  
    public Integer getActorId(){  
      return actorId;  
    }  
    
    public void setActorId(Integer actorId){  
      this.actorId = actorId;  
    } 
     
    public String getFirstName(){  
      return firstName;  
    }  
    
    public void setFirstName(String firstName){  
      this.firstName = firstName;  
    } 
     
    public String getLastName(){  
      return lastName;  
    }  
    
    public void setLastName(String lastName){  
      this.lastName = lastName;  
    } 
     
    public Date getLastUpdate(){  
      return lastUpdate;  
    }  
    
    public void setLastUpdate(Date lastUpdate){  
      this.lastUpdate = lastUpdate;  
    } 
     

    @Override
    public String toString() {
        return "Actor[" +
                "actorId = " + actorId
                 + ",firstName = " + firstName
                 + ",lastName = " + lastName
                 + ",lastUpdate = " + lastUpdate
        + "]";
    }
}  