/*
 * Copyright https://github.com/stathry/generator All rights reserved.
 */
package org.stathry.commons.pojo;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.Date;
import java.util.Objects;

/**
 * 
 * @author Auto-generated by FreeMarker
 * @date 2018-07-20 10:26
 */

@Document(collection = "actor")
public class Actor2 {

    @Id
    private String id;
    /**  */
    private Integer actorId;

    /**  */
    private String firstName;

    /**  */
    private String lastName;

    /**  */
    private Date lastUpdate;

    public Actor2(Integer actorId, String firstName, String lastName, Date lastUpdate) {
        this.actorId = actorId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.lastUpdate = lastUpdate;
    }

    public Actor2() {
    }

    public Integer getActorId(){
      return actorId;  
    }  
    
    public void setActorId(Integer actorId){  
      this.actorId = actorId;  
    } 
     
    public String getFirstName(){  
      return firstName;  
    }  
    
    public void setFirstName(String firstName){  
      this.firstName = firstName;  
    } 
     
    public String getLastName(){  
      return lastName;  
    }  
    
    public void setLastName(String lastName){  
      this.lastName = lastName;  
    } 
     
    public Date getLastUpdate(){  
      return lastUpdate;  
    }  
    
    public void setLastUpdate(Date lastUpdate){  
      this.lastUpdate = lastUpdate;  
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Actor2 actor = (Actor2) o;
        return Objects.equals(actorId, actor.actorId) &&
                Objects.equals(firstName, actor.firstName) &&
                Objects.equals(lastName, actor.lastName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(actorId, firstName, lastName);
    }

    @Override
    public String toString() {
        return "Actor2{" +
                "id='" + id + '\'' +
                ", actorId=" + actorId +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", lastUpdate=" + lastUpdate +
                '}';
    }
}  