/*
 * Copyright https://github.com/stathry/generator All rights reserved.
 */
package org.stathry.commons.dao;

import org.stathry.commons.model.City;

/**
 * 
 * @author Auto-generated by FreeMarker
 * @date 2018-07-20 10:26
 */

public interface CityDAO extends GenericDAO<City, Integer> {


}  