/*
 * Copyright https://github.com/stathry/generator All rights reserved.
 */
package org.stathry.commons.dao;

import org.apache.ibatis.annotations.Param;
import org.stathry.commons.model.City;

import java.util.Map;

/**
 * @author Auto-generated by FreeMarker
 * @date 2018-07-20 10:26
 */

public interface CityDAO extends GenericDAO<City, Integer> {

    int updatePopulation(City city);

    int updatePopulation2(@Param("id") Integer id, @Param("population") Integer population);

    int updatePopulation3(Map<String, Object> map);

}  