/*
 * Copyright https://github.com/stathry/generator All rights reserved.
 */
package org.stathry.commons.mapper.impl;

import org.springframework.stereotype.Repository;
import org.stathry.commons.mapper.CityMapper;
import org.stathry.commons.model.City;

import java.util.Map;

/**
 * @author Auto-generated by FreeMarker
 * @date 2018-07-20 10:26
 */
@Repository
public class CityMapperImpl extends GenericMapperImpl<City, Integer> implements CityMapper {

    private CityMapper mapper;

    public CityMapperImpl() {
        super();
        mapper = getMapper(CityMapper.class);
    }

    @Override
    public int updatePopulation(City city) {
        return mapper.updatePopulation(city);
    }

    @Override
    public int updatePopulation2(Integer id, Integer population) {
        return mapper.updatePopulation2(id, population);
    }

    @Override
    public int updatePopulation3(Map<String, Object> map) {
        return mapper.updatePopulation3(map);
    }

}