/*
 * Copyright https://github.com/stathry/generator All rights reserved.
 */
package org.stathry.commons.mapper;

import org.stathry.commons.model.Country;

/**
 * @author Auto-generated by FreeMarker
 * @date 2018-07-20 10:26
 */

public interface CountryMapper extends GenericMapper<Country, String> {


}  