/*
 * Copyright https://github.com/stathry/generator All rights reserved.
 */
package org.stathry.commons.model;

import java.util.Date;
import java.util.Objects;

/**
 * @author Auto-generated by FreeMarker
 * @date 2018-07-20 10:26
 */

public class Actor {

    /**  */
    private Integer actorId;

    /**  */
    private String firstName;

    /**  */
    private String lastName;

    /**  */
    private Date lastUpdate;

    public Actor() {
    }

    public Actor(Integer actorId, String firstName, String lastName, Date lastUpdate) {
        this.actorId = actorId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.lastUpdate = lastUpdate;
    }

    public Integer getActorId() {
        return actorId;
    }

    public void setActorId(Integer actorId) {
        this.actorId = actorId;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Date getLastUpdate() {
        return lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Actor actor = (Actor) o;
        return Objects.equals(actorId, actor.actorId) &&
                Objects.equals(firstName, actor.firstName) &&
                Objects.equals(lastName, actor.lastName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(actorId, firstName, lastName);
    }

    @Override
    public String toString() {
        return "Actor[" +
                "actorId = " + actorId
                + ",firstName = " + firstName
                + ",lastName = " + lastName
                + ",lastUpdate = " + lastUpdate
                + "]";
    }
}  