/*
 * Copyright https://github.com/stathry/smartj All rights reserved.
 */
package org.stathry.commons.model;

import java.util.Date;

/**
 * 
 * @author Auto-generated by FreeMarker
 * @date 2018-11-29 16:16
 */  
 
public class Country {
    
    private String code;
    
    private String name;
    
    private String continent;
    
    private String region;
    
    private Float surfaceArea;
    
    private Integer indepYear;
    
    private Integer population;
    
    private Float lifeExpectancy;
    
    private Float gnp;
    
    private Float gNPOld;
    
    private String localName;
    
    private String governmentForm;
    
    private String headOfState;
    
    private Integer capital;
    
    private String code2;
    public String getCode(){  
      return code;  
    }  
    
    public void setCode(String code){  
      this.code = code;  
    } 
     
    public String getName(){  
      return name;  
    }  
    
    public void setName(String name){  
      this.name = name;  
    } 
     
    public String  getContinent(){
      return continent;  
    }  
    
    public void setContinent(String continent){
      this.continent = continent;  
    } 
     
    public String getRegion(){  
      return region;  
    }  
    
    public void setRegion(String region){  
      this.region = region;  
    } 
     
    public Float getSurfaceArea(){  
      return surfaceArea;  
    }  
    
    public void setSurfaceArea(Float surfaceArea){  
      this.surfaceArea = surfaceArea;  
    } 
     
    public Integer getIndepYear(){  
      return indepYear;  
    }  
    
    public void setIndepYear(Integer indepYear){  
      this.indepYear = indepYear;  
    } 
     
    public Integer getPopulation(){  
      return population;  
    }  
    
    public void setPopulation(Integer population){  
      this.population = population;  
    } 
     
    public Float getLifeExpectancy(){  
      return lifeExpectancy;  
    }  
    
    public void setLifeExpectancy(Float lifeExpectancy){  
      this.lifeExpectancy = lifeExpectancy;  
    } 
     
    public Float getGnp(){  
      return gnp;  
    }  
    
    public void setGnp(Float gnp){  
      this.gnp = gnp;  
    } 
     
    public Float getGNPOld(){  
      return gNPOld;  
    }  
    
    public void setGNPOld(Float gNPOld){  
      this.gNPOld = gNPOld;  
    } 
     
    public String getLocalName(){  
      return localName;  
    }  
    
    public void setLocalName(String localName){  
      this.localName = localName;  
    } 
     
    public String getGovernmentForm(){  
      return governmentForm;  
    }  
    
    public void setGovernmentForm(String governmentForm){  
      this.governmentForm = governmentForm;  
    } 
     
    public String getHeadOfState(){  
      return headOfState;  
    }  
    
    public void setHeadOfState(String headOfState){  
      this.headOfState = headOfState;  
    } 
     
    public Integer getCapital(){  
      return capital;  
    }  
    
    public void setCapital(Integer capital){  
      this.capital = capital;  
    } 
     
    public String getCode2(){  
      return code2;  
    }  
    
    public void setCode2(String code2){  
      this.code2 = code2;  
    } 
     
    @Override
    public String toString() {
        return "Country[" +  "code = " + code
          + ", name = " + name
          + ", continent = " + continent
          + ", region = " + region
          + ", surfaceArea = " + surfaceArea
          + ", indepYear = " + indepYear
          + ", population = " + population
          + ", lifeExpectancy = " + lifeExpectancy
          + ", gnp = " + gnp
          + ", gNPOld = " + gNPOld
          + ", localName = " + localName
          + ", governmentForm = " + governmentForm
          + ", headOfState = " + headOfState
          + ", capital = " + capital
          + ", code2 = " + code2
         + "]";
    }
}  