/*
 * Copyright https://github.com/stathry/generator All rights reserved.
 */
package org.stathry.commons.dao.impl;

import org.springframework.stereotype.Repository;
import org.stathry.commons.dao.ActorDAO;
import org.stathry.commons.pojo.Actor;

/**
 * 
 * @author Auto-generated by FreeMarker
 * @date 2018-07-20 10:26
 */  
@Repository
public class ActorDAOImpl extends GenericDAOImpl<Actor, Long> implements ActorDAO {

//    private int n1 = mn1();
//    private static int n2 = mn2();

    private int mn1() {
        throw new NullPointerException();
    }

    private static int mn2() {
        throw new NullPointerException();
    }

}  