/*
 * Copyright https://github.com/stathry/generator All rights reserved.
 */
package org.stathry.commons.dao.impl;

import org.springframework.stereotype.Repository;
import org.stathry.commons.dao.CityDAO;
import org.stathry.commons.model.City;

/**
 * @author Auto-generated by FreeMarker
 * @date 2018-07-20 10:26
 */
@Repository
public class CityDAOImpl extends GenericDAOImpl<City, Integer> implements CityDAO {


}  