/*
 * Copyright https://github.com/stathry/generator All rights reserved.
 */
package org.stathry.commons.dao.impl;

import org.springframework.stereotype.Repository;
import org.stathry.commons.dao.CityDAO;
import org.stathry.commons.model.City;

import java.util.List;
import java.util.Map;

/**
 * @author Auto-generated by FreeMarker
 * @date 2018-07-20 10:26
 */
@Repository
public class CityDAOImpl extends GenericDAOImpl<City, Integer> implements CityDAO {

    private CityDAO mapper;

    public CityDAOImpl() {
        super();
        mapper = getMapper(CityDAO.class);
    }

    @Override
    public int updatePopulation(City city) {
        return mapper.updatePopulation(city);
    }

    @Override
    public int updatePopulation2(Integer id, Integer population) {
        return mapper.updatePopulation2(id, population);
    }

    @Override
    public int updatePopulation3(Map<String, Object> map) {
        return mapper.updatePopulation3(map);
    }

}